# Generated by Django 3.1.7 on 2021-03-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=30, verbose_name='상품 이름')),
                ('price', models.CharField(max_length=30, verbose_name='가격')),
                ('main_image', models.CharField(max_length=255, verbose_name='메인 이미지')),
                ('video_url', models.CharField(max_length=255, verbose_name='영상 url')),
                ('text', models.TextField(verbose_name='상품 설명')),
                ('isSell', models.BooleanField(verbose_name='판매 여부')),
            ],
            options={
                'verbose_name': '상품 정보',
                'verbose_name_plural': '상품 정보',
                'db_table': 'product_info',
            },
        ),
    ]
