# Generated by Django 3.1.7 on 2021-03-08 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('image', models.CharField(max_length=255, verbose_name='이미지 url')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productinfo')),
            ],
            options={
                'verbose_name': '상품 이미지',
                'verbose_name_plural': '상품 이미지',
                'db_table': 'product_image',
            },
        ),
    ]
