# Generated by Django 3.1.7 on 2021-03-08 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=30, verbose_name='세척 이름')),
                ('main_image', models.CharField(max_length=255, verbose_name='메인 이미지')),
                ('text', models.TextField(verbose_name='설명')),
                ('video_url', models.CharField(max_length=255, verbose_name='영상 url')),
                ('product', models.ManyToManyField(to='main.ProductInfo')),
            ],
            options={
                'verbose_name': '세척 정보',
                'verbose_name_plural': '세척 정보',
                'db_table': 'use_info',
            },
        ),
        migrations.CreateModel(
            name='CleanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('count', models.IntegerField(verbose_name='수량')),
                ('clean_type', models.CharField(choices=[('BASIC 코스', 'basic'), ('PREMIUM 코스', 'premium')], max_length=15)),
                ('isVideo', models.BooleanField(verbose_name='비디오 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '세척 신청',
                'verbose_name_plural': '세척 신청',
                'db_table': 'clean_info',
            },
        ),
        migrations.CreateModel(
            name='CleanImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('image', models.CharField(max_length=255, verbose_name='이미지 url')),
                ('clean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.useinfo')),
            ],
            options={
                'verbose_name': '세척 이미지',
                'verbose_name_plural': '세척 이미지',
                'db_table': 'use_image',
            },
        ),
    ]
