# Generated by Django 3.1.7 on 2021-03-09 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_cleanimage_cleaninfo_useinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('type', models.CharField(max_length=10, verbose_name='로그인 타입')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '유저 추가정보',
                'verbose_name_plural': '유저 추가정보',
                'db_table': 'auth_user_info',
            },
        ),
        migrations.AlterField(
            model_name='cleaninfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userinfo'),
        ),
    ]
